//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string CIN { get; set; }
        public string Email { get; set; }
        public int ID { get; set; }
    }
}
