//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaire
    {
        public int Id { get; set; }
        public string nomComplet { get; set; }
        public Nullable<int> Idgrp { get; set; }
    
        public virtual groupe groupe { get; set; }
    }
}
