//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projets
    {
        public Projets()
        {
            this.Tache = new HashSet<Tache>();
        }
    
        public int Id_Projets { get; set; }
        public string Titre { get; set; }
        public Nullable<int> Nombre_Jours_Realisation { get; set; }
    
        public virtual ICollection<Tache> Tache { get; set; }
    }
}
