//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaires
    {
        public int Id_Stagiaire { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Cin { get; set; }
        public string Ville { get; set; }
        public Nullable<System.DateTime> Date_Naissance { get; set; }
        public string E_Mail { get; set; }
        public Nullable<int> Tel_Fixe { get; set; }
        public Nullable<int> Tel_Portable { get; set; }
    }
}
