//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tache
    {
        public int Id_Tache { get; set; }
        public string Titre { get; set; }
        public Nullable<int> Projets_Id { get; set; }
        public Nullable<int> Nombre_Jours_Realisation { get; set; }
    
        public virtual Projets Projets { get; set; }
    }
}
