//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_CRYSTALE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persone
    {
        public int id { get; set; }
        public string Nom { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
