//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Editeur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int id { get; set; }
        public string Titre { get; set; }
        public string Categorie { get; set; }
        public Nullable<int> idEdit { get; set; }
    
        public virtual Editeur Editeur { get; set; }

        public override string ToString()
        {
            return id + "  /  " + Titre + "  /  " + Categorie + "  /  " + idEdit;
        }
    }
}
