//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_1_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public int id { get; set; }
        public Nullable<int> solde { get; set; }
    }
}
