//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tpra
{
    using System;
    using System.Collections.Generic;
    
    public partial class banq
    {
        public int Id { get; set; }
        public Nullable<int> FacId { get; set; }
        public string Nom { get; set; }
    
        public virtual facture facture { get; set; }
    }
}
