//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaidKaliniEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formateur
    {
        public int IdFormateur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Tele { get; set; }
        public override string ToString()
        {
            return $"Nom de formateur {Nom} {Prenom} ";
        }
    }
}
