//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmploye
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int IdE { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> tel { get; set; }
        public string adresse { get; set; }
        public Nullable<int> IDS { get; set; }
    
        public virtual Salaire Salaire { get; set; }
        public Employe() { }
        public Employe (int ide, string nom, string pre , int tel, string adres , int ids)
        {
            this.IdE = ide;
            this.Nom = nom;
            this.Prenom = pre;
            this.adresse = adres;
            this.tel = tel;
            this.IDS = ide;
        }
        public override string ToString()
        {
            return IdE + " " + Nom + " " + Prenom + " " + tel + " " + adresse + " " + IDS ;
        }
    }
}
