//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int Id { get; set; }
        public string Etud_Name { get; set; }
        public string Etud_Tel { get; set; }
    
        public virtual Etablissement1 Etablissement1 { get; set; }
    }
}
