//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameWorke
{
    using System;
    using System.Collections.Generic;
    
    public partial class elive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public elive()
        {
            this.lecon = new HashSet<lecon>();
        }
    
        public int idelive { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string rue { get; set; }
        public string ville { get; set; }
        public Nullable<int> cp { get; set; }
        public Nullable<decimal> credithoraire { get; set; }
        public Nullable<System.DateTime> dateinscription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lecon> lecon { get; set; }
    }
}
