//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editeur
    {
        public int id { get; set; }
        public string Nom { get; set; }
        public string categorie { get; set; }
        public Nullable<int> id_livre { get; set; }
    
        public virtual Livre Livre { get; set; }
    }
}
