//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagaire
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string cin { get; set; }

        public Stagaire()
        {

        }
        public Stagaire(int id, string nom, string cin)
        {
            this.id = id;
            this.nom = nom;
            this.cin = cin;
        }

        public override string ToString()
        {
            return "Id:" + id + " Nom:" + nom + " Cin:" + cin;
        }
    }
}
